[toolchain]
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
collection_prices = "2pSMcVgAmeidrymy7XbqLfi4GLuCtmDATHXEHPXQYjw3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/mnt/d/Github/anchorWorld/wallets/devent-test-wallets/devenet-wallet-1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
